@web = http://127.0.0.1:3000/api/web/
@admin = http://127.0.0.1:3000/api/admin/

@jsonType = Content-Type: application/json

###
GET {{web}}getArticle

###文章管理
POST  {{admin}}/role/list
{{jsonType}}

{
  "title":"test",
  "count":1
}

###
GET  {{web}}getTagList